Alaris::Calculator::node::ANumberExp
TNumber Alaris::Calculator::node.ANumberExp::_number_
Alaris.Calculator.node.ANumberExp.ANumberExp()
Alaris.Calculator.node.ANumberExp.ANumberExp(TNumber _number_)
override Object Alaris.Calculator.node.ANumberExp.Clone()
override void Alaris.Calculator.node.ANumberExp.Apply(Switch sw)
TNumber Alaris.Calculator.node.ANumberExp.GetNumber()
Referenced by Alaris.Calculator.analysis.ReversedDepthFirstAdapter::CaseANumberExp, Alaris.Calculator.analysis.DepthFirstAdapter::CaseANumberExp, Alaris.Calculator.AstCalculator::InANumberExp.
void Alaris.Calculator.node.ANumberExp.SetNumber(TNumber node)
References Alaris.Calculator.node.Node::Parent.
override string Alaris.Calculator.node.ANumberExp.ToString()
Alaris.Calculator.node.ANumberExp.ANumberExp()
Alaris.Calculator.node.ANumberExp.ANumberExp(TNumber _number_)
override Object Alaris.Calculator.node.ANumberExp.Clone()
override void Alaris.Calculator.node.ANumberExp.Apply(Switch sw)
TNumber Alaris.Calculator.node.ANumberExp.GetNumber()
void Alaris.Calculator.node.ANumberExp.SetNumber(TNumber node)
References Alaris.Calculator.node.Node::Parent.
override string Alaris.Calculator.node.ANumberExp.ToString()
internal override void Alaris.Calculator.node.ANumberExp.RemoveChild(Node child)
internal override void Alaris.Calculator.node.ANumberExp.ReplaceChild(Node oldChild, Node newChild)
internal override void Alaris.Calculator.node.ANumberExp.RemoveChild(Node child)
internal override void Alaris.Calculator.node.ANumberExp.ReplaceChild(Node oldChild, Node newChild)