Alaris::Irc::Connection
RawMessageReceivedEventHandler Alaris.Irc.Connection.OnRawMessageReceived
Receive all the messages, unparsed, sent by the IRC server. This is not normally needed but provided for those who are interested.
RawMessageSentEventHandler Alaris.Irc.Connection.OnRawMessageSent
Receive all the raw messages sent to the IRC from this connection.
TcpClient Alaris.Irc.Connection._client
readonly Regex Alaris.Irc.Connection._propertiesRegex
readonly Listener Alaris.Irc.Connection._listener
readonly Sender Alaris.Irc.Connection._sender
CtcpListener Alaris.Irc.Connection._ctcpListener
CtcpSender Alaris.Irc.Connection._ctcpSender
CtcpResponder Alaris.Irc.Connection._ctcpResponder
bool Alaris.Irc.Connection._ctcpEnabled
bool Alaris.Irc.Connection._dccEnabled
Thread Alaris.Irc.Connection._socketListenThread
StreamReader Alaris.Irc.Connection._reader
DateTime Alaris.Irc.Connection._timeLastSent
bool Alaris.Irc.Connection._registered
bool Alaris.Irc.Connection._connected
bool Alaris.Irc.Connection._handleNickFailure
readonly ArrayList Alaris.Irc.Connection._parsers
ServerProperties Alaris.Irc.Connection._properties
StreamWriter Alaris.Irc.Connection._writer
internal ConnectionArgs Alaris.Irc.Connection.ConnectionArgs
Encoding Alaris.Irc.Connection.TextEncoding
Sets the text encoding used by the read and write streams. Must be set before Connect() is called and should not be changed while the connection is processing messages.
An Encoding constant.
bool Alaris.Irc.Connection.Registered
A read-only property indicating whether the connection has been opened with the IRC server and the client has been successfully registered.
True if the client is connected and registered.
bool Alaris.Irc.Connection.Connected
A read-only property indicating whether a connection has been opened with the IRC server (but not whether registration has succeeded).
True if the client is connected.
bool Alaris.Irc.Connection.HandleNickTaken
By default the connection itself will handle the case where, while attempting to register the client's nick is already in use. It does this by simply appending 2 random numbers to the end of the nick.
The NickError event is shows that the nick collision has happened and it is fixed by calling Sender's Register() method passing in the replacement nickname.True if the connection should handle this case and false if the client will handle it itself.
string Alaris.Irc.Connection.Name
A user friendly name of this Connection in the form 'nick'.
Read only string
bool Alaris.Irc.Connection.EnableCtcp
Whether Ctcp commands should be processed and if Ctcp events will be raised.
True will enable the CTCP sender and listener and false will cause their property calls to return null.
Referenced by Alaris.Irc.Ctcp.CtcpResponder::CtcpResponder.
bool Alaris.Irc.Connection.EnableDcc
Whether DCC requests should be processed or ignored by this Connection. Since the DccListener is a singleton and shared by all Connections, listeners to DccListener events should be manually removed when no longer needed.
True to process DCC requests.
CtcpResponder Alaris.Irc.Connection.CtcpResponder
Sets an automatic responder to Ctcp queries.
Once this is set it can be removed by setting it to null.
TimeSpan Alaris.Irc.Connection.IdleTime
The amount of time that has passed since the client sent a command to the IRC server.
Read only TimeSpan
Sender Alaris.Irc.Connection.Sender
The object used to send commands to the IRC server.
Read-only Sender.
Referenced by Alaris.Irc.Dcc.DccFileSession::Get, Alaris.Commands.BasicCommands::HandleHelpCommand, Alaris.Commands.BasicCommands::HandleJoinCommand.
Listener Alaris.Irc.Connection.Listener
The object that parses messages and notifies the appropriate delegate.
Read only Listener.
CtcpSender Alaris.Irc.Connection.CtcpSender
The object used to send CTCP commands to the IRC server.
Read only CtcpSender. Null if CtcpEnabled is false.
CtcpListener Alaris.Irc.Connection.CtcpListener
The object that parses CTCP messages and notifies the appropriate delegate.
Read only CtcpListener. Null if CtcpEnabled is false.
Referenced by Alaris.Irc.Ctcp.CtcpResponder::CtcpResponder.
ConnectionArgs Alaris.Irc.Connection.ConnectionData
The collection of data used to establish this connection.
Read only ConnectionArgs.
ServerProperties Alaris.Irc.Connection.ServerProperties
A read-only collection of string key/value pairs representing IRC server proprties.
This connection's ServerProperties obejct or null if it has not been created.
internal Alaris.Irc.Connection.Connection(ConnectionArgs args)
Used for internal test purposes only.
bool Alaris.Irc.Connection.CustomParse(string line)
void Alaris.Irc.Connection.KeepAlive(string message)
Respond to IRC keep-alives.
message The message that should be echoed back
void Alaris.Irc.Connection.MyNickChanged(UserInfo user, string newNick)
Update the ConnectionArgs object when the user changes his nick.
user Who changed their nick newNick The new nick name
void Alaris.Irc.Connection.OnRegistered()
void Alaris.Irc.Connection.OnNickError(string badNick, string reason)
badNick reason
void Alaris.Irc.Connection.OnReply(ReplyCode code, string info)
Listen for the 005 info messages sent during registration so that the maximum lengths of certain items (Nick, Away, Topic) can be determined dynamically.
code Reply code enum info An info line
void Alaris.Irc.Connection.RegisterDelegates()
internal void Alaris.Irc.Connection.ReceiveIRCMessages()
Read in message lines from the IRC server and send them to a parser for processing. Discard CTCP and DCC messages if these protocols are not enabled.
internal void Alaris.Irc.Connection.SendCommand(StringBuilder command)
Send a message to the IRC server and clear the command buffer.
internal void Alaris.Irc.Connection.SendAutomaticReply(StringBuilder command)
Send a message to the IRC server which does not affect the client's idle time. Used for automatic replies such as PONG or Ctcp repsones.
Alaris.Irc.Connection.Connection(ConnectionArgs args, bool enableCtcp, bool enableDcc)
Prepare a connection to an IRC server but do not open it. This sets the text Encoding to Default.
args The set of information need to connect to an IRC server enableCtcp True if this Connection should support CTCP. enableDcc True if this Connection should support DCC.
Alaris.Irc.Connection.Connection(Encoding textEncoding, ConnectionArgs args, bool enableCtcp, bool enableDcc)
Prepare a connection to an IRC server but do not open it.
args The set of information need to connect to an IRC server enableCtcp True if this Connection should support CTCP. enableDcc True if this Connection should support DCC. textEncoding The text encoding for the incoming stream.
void Alaris.Irc.Connection.Connect()
Connect to the IRC server and start listening for messages on a new thread.
SocketException If a connection cannot be established with the IRC server
void Alaris.Irc.Connection.Disconnect(string reason)
Sends a 'Quit' message to the server, closes the connection, and stops the listening thread.
The state of the connection will remain the same even after a disconnect, so the connection can be reopened. All the event handlers will remain registered. reason A message displayed to IRC users upon disconnect.
Referenced by Alaris.AlarisBot::Disconnect.
override string Alaris.Irc.Connection.ToString()
A friendly name for this connection.
The Name property
Referenced by Alaris.Irc.Dcc.DccUserInfo::ToString.
void Alaris.Irc.Connection.AddParser(IParser parser)
Adds a parser class to a list of custom parsers. Any number can be added. The custom parsers will be tested using CanParse() before the default parsers. The last parser to be added will be the first to process a message.
parser Any class that implements IParser.
void Alaris.Irc.Connection.RemoveParser(IParser parser)
Remove a custom parser class.
parser Any class that implements IParser.
void Alaris.Irc.Connection.Dispose()
Referenced by Alaris.AlarisBot::Dispose.
static void Alaris.Irc.Connection.ExtractProperties()