MvpXml::XPathNavigatorReader
XPathNavigator MvpXml.XPathNavigatorReader._navigator
XPathNavigator MvpXml.XPathNavigatorReader._original
bool MvpXml.XPathNavigatorReader._fragment
bool MvpXml.XPathNavigatorReader._isendelement
ArrayList MvpXml.XPathNavigatorReader._orderedattributes
int MvpXml.XPathNavigatorReader._depth
bool MvpXml.XPathNavigatorReader._eof
ReadState MvpXml.XPathNavigatorReader._state
bool MvpXml.XPathNavigatorReader._attributevalueread
ArrayList MvpXml.XPathNavigatorReader.OrderedAttributes
Retrieves and caches node positions and their name/ns.
override int MvpXml.XPathNavigatorReader.AttributeCount
See XmlReader.AttributeCount
override string MvpXml.XPathNavigatorReader.BaseURI
See XmlReader.BaseURI
override int MvpXml.XPathNavigatorReader.Depth
See XmlReader.Depth
override bool MvpXml.XPathNavigatorReader.EOF
See XmlReader.EOF
override bool MvpXml.XPathNavigatorReader.HasValue
See XmlReader.HasValue
override bool MvpXml.XPathNavigatorReader.HasAttributes
See XmlReader.HasAttributes
override bool MvpXml.XPathNavigatorReader.IsDefault
See XmlReader.IsDefault
override bool MvpXml.XPathNavigatorReader.IsEmptyElement
See XmlReader.IsDefault
override string MvpXml.XPathNavigatorReader::this[string name, string namespaceURI]
See XmlReader.this
override string MvpXml.XPathNavigatorReader.LocalName
See XmlReader.LocalName
override string MvpXml.XPathNavigatorReader.Name
See XmlReader.Name
override string MvpXml.XPathNavigatorReader.NamespaceURI
See XmlReader.NamespaceURI
override XmlNameTable MvpXml.XPathNavigatorReader.NameTable
See XmlReader.NameTable
override XmlNodeType MvpXml.XPathNavigatorReader.NodeType
See XmlReader.NodeType
override string MvpXml.XPathNavigatorReader.Prefix
See XmlReader.Prefix
override char MvpXml.XPathNavigatorReader.QuoteChar
See XmlReader.QuoteChar
override ReadState MvpXml.XPathNavigatorReader.ReadState
See XmlReader.ReadState
Referenced by MvpXml.XPathNavigatorReader::Close, MvpXml.XPathNavigatorReader::Read, MvpXml.XPathNavigatorReader::ReadOuterXml.
override string MvpXml.XPathNavigatorReader.Value
See XmlReader.Value
override string MvpXml.XPathNavigatorReader.XmlLang
See XmlReader.XmlLang
override XmlSpace MvpXml.XPathNavigatorReader.XmlSpace
See XmlReader.XmlSpace
MvpXml.XPathNavigatorReader.XPathNavigatorReader()
Parameterless constructor for XML serialization.
Supports the .NET serialization infrastructure. Don't use this constructor in your regular application.
MvpXml.XPathNavigatorReader.XPathNavigatorReader(XPathNavigator navigator)
Initializes the reader.
navigator The navigator to expose as a reader.
MvpXml.XPathNavigatorReader.XPathNavigatorReader(XPathNavigator navigator, bool readFragment)
Initializes the reader.
navigator The navigator to expose as a reader. readFragment Specifies that the reader should expose as an XML fragment the current navigator node and all its following siblings.
string MvpXml.XPathNavigatorReader.ReadFragmentXml()
Reads the current node and all its siblings, and returns the XML for them as a fragment.
Referenced by MvpXml.XPathNavigatorReader::ReadInnerXml.
override void MvpXml.XPathNavigatorReader.Close()
See XmlReader.Close
References MvpXml.XPathNavigatorReader::ReadState.
override string MvpXml.XPathNavigatorReader.GetAttribute(string name, string namespaceURI)
See XmlReader.GetAttribute
override string MvpXml.XPathNavigatorReader.GetAttribute(string name)
See XmlReader.GetAttribute
override string MvpXml.XPathNavigatorReader.GetAttribute(int i)
See XmlReader.GetAttribute
override string MvpXml.XPathNavigatorReader.LookupNamespace(string prefix)
See XmlReader.LookupNamespace
override bool MvpXml.XPathNavigatorReader.MoveToAttribute(string name, string ns)
See XmlReader.MoveToAttribute
Referenced by MvpXml.XPathNavigatorReader::MoveToAttribute.
override bool MvpXml.XPathNavigatorReader.MoveToAttribute(string name)
See XmlReader.MoveToAttribute
References MvpXml.XPathNavigatorReader::MoveToAttribute.
override void MvpXml.XPathNavigatorReader.MoveToAttribute(int i)
See XmlReader.MoveToAttribute
References MvpXml.XPathNavigatorReader::MoveToAttribute.
override bool MvpXml.XPathNavigatorReader.MoveToElement()
See XmlReader.MoveToElement
override bool MvpXml.XPathNavigatorReader.MoveToFirstAttribute()
See XmlReader.MoveToFirstAttribute
References MvpXml.XPathNavigatorReader::MoveToNextAttribute.
Referenced by MvpXml.XPathNavigatorReader::MoveToNextAttribute.
override bool MvpXml.XPathNavigatorReader.MoveToNextAttribute()
See XmlReader.MoveToNextAttribute
References MvpXml.XPathNavigatorReader::MoveToFirstAttribute.
Referenced by MvpXml.XPathNavigatorReader::MoveToFirstAttribute.
override bool MvpXml.XPathNavigatorReader.Read()
See XmlReader.Read
References MvpXml.XPathNavigatorReader::ReadState.
Referenced by MvpXml.XPathNavigatorReader::ReadInnerXml.
override bool MvpXml.XPathNavigatorReader.ReadAttributeValue()
See XmlReader.ReadAttributeValue
override string MvpXml.XPathNavigatorReader.ReadInnerXml()
See XmlReader.ReadInnerXml
References MvpXml.XPathNavigatorReader::Read, MvpXml.XPathNavigatorReader::ReadFragmentXml.
override string MvpXml.XPathNavigatorReader.ReadOuterXml()
See XmlReader.ReadOuterXml
References MvpXml.XPathNavigatorReader::ReadState.
override void MvpXml.XPathNavigatorReader.ResolveEntity()
See XmlReader.Read
void IXmlSerializable. MvpXml.XPathNavigatorReader.WriteXml(XmlWriter writer)
See IXmlSerializable.WriteXml.
System.Xml.Schema.XmlSchema IXmlSerializable. MvpXml.XPathNavigatorReader.GetSchema()
See IXmlSerializable.GetSchema.
void IXmlSerializable. MvpXml.XPathNavigatorReader.ReadXml(XmlReader reader)
See IXmlSerializable.ReadXml.