Alaris::AlarisBot
Connection Alaris.AlarisBot._connection
ScriptManager Alaris.AlarisBot._manager
string Alaris.AlarisBot._nick
string Alaris.AlarisBot._server
bool Alaris.AlarisBot._confdone
bool Alaris.AlarisBot._nickserv
string Alaris.AlarisBot._nspw
readonly List<string> Alaris.AlarisBot._channels
readonly CrashHandler Alaris.AlarisBot._sCrashHandler
readonly Guid Alaris.AlarisBot._guid
readonly string Alaris.AlarisBot._configfile
const int Alaris.AlarisBot.ListenerPort
const string Alaris.AlarisBot.ACSHost
const int Alaris.AlarisBot.ACSPort
string Alaris.AlarisBot._scriptsDir
string Alaris.AlarisBot.DBName
Database name.
bool Alaris.AlarisBot.LuaEnabled
Gets whether the Lua engine is enabled or not.
string Alaris.AlarisBot.RemoteName
Gets the remote's name.
int Alaris.AlarisBot.RemotePort
Gets the remote's port.
string Alaris.AlarisBot.RemotePassword
Gets the remote's password.
CrashHandler Alaris.AlarisBot.CrashHandler
The bot's crash handler instance.
string Alaris.AlarisBot.Locale
Gets the current locale.
Referenced by Alaris.Commands.BasicCommands::HandleHelpCommand.
ScriptManager Alaris.AlarisBot.ScriptManager
The bot's script manager instance.
List<string> Alaris.AlarisBot.Channels
Gets the list of channels the bot is on.
Connection Alaris.AlarisBot.Connection
Gets the IRC connection.
CThreadPool Alaris.AlarisBot.Pool
Gets or sets the thread pool.
The thread pool.
Referenced by Alaris.AlarisBot::Disconnect.
static AlarisBot Alaris.AlarisBot.GetBot()
Returns the bot instance.
The bot
static int Alaris.AlarisBot.GetListenerPort()
Gets the listener port.
The listener port.
Alaris.AlarisBot.AlarisBot()
This is not an unused constructor. Called through singleton!
Alaris.AlarisBot.AlarisBot(string config)
Creates a new instacne of Alaris bot.
Alaris.AlarisBot.~AlarisBot()
Releases unmanaged resources and performs other cleanup operations before the AlarisBot is reclaimed by garbage collection.
void Alaris.AlarisBot.SetupHandlers()
void Alaris.AlarisBot.ReadConfig(string configfile)
Reads and parses the specified config file.
configfile The config file name. ConfigFileInvalidException
void Alaris.AlarisBot.Connect()
Establishes the connection to the previously specified server.
void Alaris.AlarisBot.OnRegistered()
Method run when the bot is registered to the IRC server.
void Alaris.AlarisBot.OnPublicMessage(UserInfo user, string chan, string msg)
The method called when a public message occurs in one of the channels the bot is on.
user The data about the user who sent the message. chan The channel where the message occured. msg The message that was sent.
Guid Alaris.AlarisBot.GetGuid()
Gets the GUID.
void Alaris.AlarisBot.Run()
Run this instance.
void Alaris.AlarisBot.Disconnect(string rsr)
Disconnects the bot from the IRC server.
rsr Reason for disconnect.
References Alaris.Irc.Connection::Disconnect, Alaris.Threading.CThreadPool::Free, Alaris.AlarisBot::Pool.
Referenced by Alaris.Commands.BasicCommands::HandleQuitCommand.
void Alaris.AlarisBot.Dispose()
Releases all used resources.
References Alaris.Irc.Connection::Dispose.
void Alaris.AlarisBot.SendMsg(string channel, string message)
Sends the given message to the specified channel.
channel A System.String message A System.String
Referenced by Alaris.Commands.AdvancedCommands::HandleAdminCommands, Alaris.Commands.AdvancedCommands::HandleAesCommands.
static void Alaris.AlarisBot.OnCtcpRequest(string command, UserInfo user)
Method run when the bot receives a CTCP request.
command The CTCP command. user Data about the user who sent it.