Emil::GMP::BigInt
const string Emil.GMP.BigInt.MPZ_LIBRARY_PATH
const int Emil.GMP.BigInt.s_defaultStringBase
const int Emil.GMP.BigInt.s_chunkBitLength
MpzValue Emil.GMP.BigInt.InternalValue
readonly BigInt Emil.GMP.BigInt.NegativeTen
readonly BigInt Emil.GMP.BigInt.NegativeThree
readonly BigInt Emil.GMP.BigInt.NegativeTwo
readonly BigInt Emil.GMP.BigInt.NegativeOne
readonly BigInt Emil.GMP.BigInt.Zero
readonly BigInt Emil.GMP.BigInt.One
readonly BigInt Emil.GMP.BigInt.Two
readonly BigInt Emil.GMP.BigInt.Three
readonly BigInt Emil.GMP.BigInt.Ten
int Emil.GMP.BigInt.this[int bitIndex][int bitIndex]
bool Emil.GMP.BigInt.IsOdd
bool Emil.GMP.BigInt.IsEven
Referenced by Emil.GMP.BigInt::JacobiSymbol.
int Emil.GMP.BigInt.BitLength
static void Emil.GMP.BigInt.__gmpz_init(ref MpzValue x)
static void Emil.GMP.BigInt.__gmpz_init2(ref MpzValue x, uint n)
static void Emil.GMP.BigInt.__gmpz_init_set(ref MpzValue rop, ref MpzValue op)
static void Emil.GMP.BigInt.__gmpz_init_set_si(ref MpzValue rop, int op)
static void Emil.GMP.BigInt.__gmpz_init_set_ui(ref MpzValue rop, uint op)
static void Emil.GMP.BigInt.__gmpz_init_set_d(ref MpzValue rop, double op)
static int Emil.GMP.BigInt.__gmpz_init_set_str(ref MpzValue rop, string str, int @base)
static void Emil.GMP.BigInt.__gmpz_clear(ref MpzValue x)
static void Emil.GMP.BigInt.__gmpz_import(ref MpzValue rop, uint count, int order, uint size, int endian, uint nails, void *op)
static void* Emil.GMP.BigInt.__gmpz_export(void *rop, uint *countp, int order, uint size, int endian, uint nails, ref MpzValue op)
static void Emil.GMP.BigInt.__gmpz_neg(ref MpzValue rop, ref MpzValue op)
static void Emil.GMP.BigInt.__gmpz_abs(ref MpzValue rop, ref MpzValue op)
static uint Emil.GMP.BigInt.__gmpz_sizeinbase(ref MpzValue op, int @base)
static int Emil.GMP.BigInt.__gmpz_cmp(ref MpzValue op1, ref MpzValue op2)
static int Emil.GMP.BigInt.__gmpz_cmp_si(ref MpzValue op1, int op2)
static int Emil.GMP.BigInt.__gmpz_cmp_ui(ref MpzValue op1, uint op2)
static int Emil.GMP.BigInt.__gmpz_cmp_d(ref MpzValue op1, double op2)
static int Emil.GMP.BigInt.__gmpz_cmpabs(ref MpzValue op1, ref MpzValue op2)
static int Emil.GMP.BigInt.__gmpz_cmpabs_ui(ref MpzValue op1, uint op2)
static int Emil.GMP.BigInt.__gmpz_cmpabs_d(ref MpzValue op1, double op2)
static void Emil.GMP.BigInt.__gmpz_powm(ref MpzValue rop, ref MpzValue @base, ref MpzValue exp, ref MpzValue mod)
static void Emil.GMP.BigInt.__gmpz_powm_ui(ref MpzValue rop, ref MpzValue @base, uint exp, ref MpzValue mod)
static void Emil.GMP.BigInt.__gmpz_pow_ui(ref MpzValue rop, ref MpzValue @base, uint exp)
static void Emil.GMP.BigInt.__gmpz_ui_pow_ui(ref MpzValue rop, uint @base, uint exp)
static void Emil.GMP.BigInt.__gmpz_add(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_add_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_sub(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_ui_sub(ref MpzValue rop, uint op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_sub_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_mul(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_mul_si(ref MpzValue rop, ref MpzValue op1, int op2)
static void Emil.GMP.BigInt.__gmpz_mul_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_mul_2exp(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_addmul(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_addmul_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_submul(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_submul_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_tdiv_q(ref MpzValue q, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_tdiv_r(ref MpzValue r, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_tdiv_qr(ref MpzValue q, ref MpzValue r, ref MpzValue n, ref MpzValue d)
static uint Emil.GMP.BigInt.__gmpz_tdiv_q_ui(ref MpzValue q, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_tdiv_r_ui(ref MpzValue r, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_tdiv_qr_ui(ref MpzValue q, ref MpzValue r, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_tdiv_ui(ref MpzValue n, uint d)
static void Emil.GMP.BigInt.__gmpz_tdiv_q_2exp(ref MpzValue q, ref MpzValue n, uint b)
static void Emil.GMP.BigInt.__gmpz_tdiv_r_2exp(ref MpzValue r, ref MpzValue n, uint b)
static void Emil.GMP.BigInt.__gmpz_cdiv_q(ref MpzValue q, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_cdiv_r(ref MpzValue r, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_cdiv_qr(ref MpzValue q, ref MpzValue r, ref MpzValue n, ref MpzValue d)
static uint Emil.GMP.BigInt.__gmpz_cdiv_q_ui(ref MpzValue q, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_cdiv_r_ui(ref MpzValue r, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_cdiv_qr_ui(ref MpzValue q, ref MpzValue r, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_cdiv_ui(ref MpzValue n, uint d)
static void Emil.GMP.BigInt.__gmpz_cdiv_q_2exp(ref MpzValue q, ref MpzValue n, uint b)
static void Emil.GMP.BigInt.__gmpz_cdiv_r_2exp(ref MpzValue r, ref MpzValue n, uint b)
static void Emil.GMP.BigInt.__gmpz_fdiv_q(ref MpzValue q, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_fdiv_r(ref MpzValue r, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_fdiv_qr(ref MpzValue q, ref MpzValue r, ref MpzValue n, ref MpzValue d)
static uint Emil.GMP.BigInt.__gmpz_fdiv_q_ui(ref MpzValue q, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_fdiv_r_ui(ref MpzValue r, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_fdiv_qr_ui(ref MpzValue q, ref MpzValue r, ref MpzValue n, uint d)
static uint Emil.GMP.BigInt.__gmpz_fdiv_ui(ref MpzValue n, uint d)
static void Emil.GMP.BigInt.__gmpz_fdiv_q_2exp(ref MpzValue q, ref MpzValue n, uint b)
static void Emil.GMP.BigInt.__gmpz_fdiv_r_2exp(ref MpzValue r, ref MpzValue n, uint b)
static void Emil.GMP.BigInt.__gmpz_mod(ref MpzValue r, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_divexact(ref MpzValue q, ref MpzValue n, ref MpzValue d)
static void Emil.GMP.BigInt.__gmpz_divexact_ui(ref MpzValue q, ref MpzValue n, uint d)
static int Emil.GMP.BigInt.__gmpz_divisible_p(ref MpzValue n, ref MpzValue d)
static int Emil.GMP.BigInt.__gmpz_divisible_ui_p(ref MpzValue n, uint d)
static int Emil.GMP.BigInt.__gmpz_divisible_2exp_p(ref MpzValue n, uint b)
static int Emil.GMP.BigInt.__gmpz_congruent_p(ref MpzValue n, ref MpzValue c, ref MpzValue d)
static int Emil.GMP.BigInt.__gmpz_congruent_ui_p(ref MpzValue n, uint c, uint d)
static int Emil.GMP.BigInt.__gmpz_congruent_2exp_p(ref MpzValue n, ref MpzValue c, uint b)
static int Emil.GMP.BigInt.__gmpz_invert(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_and(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_ior(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_xor(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_com(ref MpzValue rop, ref MpzValue op)
static uint Emil.GMP.BigInt.__gmpz_popcount(ref MpzValue op)
static uint Emil.GMP.BigInt.__gmpz_hamdist(ref MpzValue op1, ref MpzValue op2)
static uint Emil.GMP.BigInt.__gmpz_scan0(ref MpzValue op, uint starting_bit)
static uint Emil.GMP.BigInt.__gmpz_scan1(ref MpzValue op, uint starting_bit)
static void Emil.GMP.BigInt.__gmpz_setbit(ref MpzValue rop, uint bit_index)
static void Emil.GMP.BigInt.__gmpz_clrbit(ref MpzValue rop, uint bit_index)
static void Emil.GMP.BigInt.__gmpz_combit(ref MpzValue rop, uint bit_index)
static int Emil.GMP.BigInt.__gmpz_tstbit(ref MpzValue rop, uint bit_index)
static uint Emil.GMP.BigInt.__gmpz_get_ui(ref MpzValue op)
static int Emil.GMP.BigInt.__gmpz_get_si(ref MpzValue op)
static double Emil.GMP.BigInt.__gmpz_get_d(ref MpzValue op)
static void* Emil.GMP.BigInt.__gmpz_get_str(StringBuilder str, int @base, ref MpzValue op)
static int Emil.GMP.BigInt.__gmpz_root(ref MpzValue rop, ref MpzValue op, uint n)
static void Emil.GMP.BigInt.__gmpz_rootrem(ref MpzValue root, ref MpzValue rem, ref MpzValue u, uint n)
static void Emil.GMP.BigInt.__gmpz_sqrt(ref MpzValue rop, ref MpzValue op)
static void Emil.GMP.BigInt.__gmpz_sqrtrem(ref MpzValue rop1, ref MpzValue rop2, ref MpzValue op)
static int Emil.GMP.BigInt.__gmpz_perfect_power_p(ref MpzValue op)
static int Emil.GMP.BigInt.__gmpz_perfect_square_p(ref MpzValue op)
static int Emil.GMP.BigInt.__gmpz_probab_prime_p(ref MpzValue n, int reps)
static void Emil.GMP.BigInt.__gmpz_nextprime(ref MpzValue rop, ref MpzValue op)
static void Emil.GMP.BigInt.__gmpz_gcd(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static uint Emil.GMP.BigInt.__gmpz_gcd_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static void Emil.GMP.BigInt.__gmpz_gcdext(ref MpzValue g, ref MpzValue s, ref MpzValue t, ref MpzValue a, ref MpzValue b)
static void Emil.GMP.BigInt.__gmpz_gcdext(ref MpzValue g, ref MpzValue s, MpzValue *t, ref MpzValue a, ref MpzValue b)
static void Emil.GMP.BigInt.__gmpz_lcm(ref MpzValue rop, ref MpzValue op1, ref MpzValue op2)
static void Emil.GMP.BigInt.__gmpz_lcm_ui(ref MpzValue rop, ref MpzValue op1, uint op2)
static int Emil.GMP.BigInt.__gmpz_jacobi(ref MpzValue a, ref MpzValue b)
static int Emil.GMP.BigInt.__gmpz_legendre(ref MpzValue a, ref MpzValue p)
static int Emil.GMP.BigInt.__gmpz_kronecker(ref MpzValue a, ref MpzValue b)
static int Emil.GMP.BigInt.__gmpz_kronecker_si(ref MpzValue a, int b)
static int Emil.GMP.BigInt.__gmpz_kronecker_ui(ref MpzValue a, uint b)
static int Emil.GMP.BigInt.__gmpz_si_kronecker(int a, ref MpzValue b)
static int Emil.GMP.BigInt.__gmpz_ui_kronecker(uint a, ref MpzValue b)
static uint Emil.GMP.BigInt.__gmpz_remove(ref MpzValue rop, ref MpzValue op, ref MpzValue f)
static void Emil.GMP.BigInt.__gmpz_fac_ui(ref MpzValue rop, uint op)
static void Emil.GMP.BigInt.__gmpz_bin_ui(ref MpzValue rop, ref MpzValue n, uint k)
static void Emil.GMP.BigInt.__gmpz_bin_uiui(ref MpzValue rop, uint n, uint k)
static void Emil.GMP.BigInt.__gmpz_fib_ui(ref MpzValue fn, uint n)
static void Emil.GMP.BigInt.__gmpz_fib2_ui(ref MpzValue fn, ref MpzValue fnsub1, uint n)
static void Emil.GMP.BigInt.__gmpz_lucnum_ui(ref MpzValue ln, uint n)
static void Emil.GMP.BigInt.__gmpz_lucnum2_ui(ref MpzValue ln, ref MpzValue lnsub1, uint n)
Emil.GMP.BigInt.~BigInt()
object ICloneable. Emil.GMP.BigInt.Clone()
TypeCode IConvertible. Emil.GMP.BigInt.GetTypeCode()
bool IConvertible. Emil.GMP.BigInt.ToBoolean(IFormatProvider provider)
byte IConvertible. Emil.GMP.BigInt.ToByte(IFormatProvider provider)
char IConvertible. Emil.GMP.BigInt.ToChar(IFormatProvider provider)
DateTime IConvertible. Emil.GMP.BigInt.ToDateTime(IFormatProvider provider)
decimal IConvertible. Emil.GMP.BigInt.ToDecimal(IFormatProvider provider)
double IConvertible. Emil.GMP.BigInt.ToDouble(IFormatProvider provider)
short IConvertible. Emil.GMP.BigInt.ToInt16(IFormatProvider provider)
int IConvertible. Emil.GMP.BigInt.ToInt32(IFormatProvider provider)
long IConvertible. Emil.GMP.BigInt.ToInt64(IFormatProvider provider)
sbyte IConvertible. Emil.GMP.BigInt.ToSByte(IFormatProvider provider)
float IConvertible. Emil.GMP.BigInt.ToSingle(IFormatProvider provider)
string IConvertible. Emil.GMP.BigInt.ToString(IFormatProvider provider)
object IConvertible. Emil.GMP.BigInt.ToType(Type targetType, IFormatProvider provider)
ushort IConvertible. Emil.GMP.BigInt.ToUInt16(IFormatProvider provider)
uint IConvertible. Emil.GMP.BigInt.ToUInt32(IFormatProvider provider)
ulong IConvertible. Emil.GMP.BigInt.ToUInt64(IFormatProvider provider)
Emil.GMP.BigInt.BigInt()
Emil.GMP.BigInt.BigInt(BigInt other)
Emil.GMP.BigInt.BigInt(int value)
Emil.GMP.BigInt.BigInt(uint value)
Emil.GMP.BigInt.BigInt(uint value, int sign)
Emil.GMP.BigInt.BigInt(float value)
Emil.GMP.BigInt.BigInt(double value)
Emil.GMP.BigInt.BigInt(decimal value)
Emil.GMP.BigInt.BigInt(long value)
Emil.GMP.BigInt.BigInt(ulong value)
Emil.GMP.BigInt.BigInt(ulong value, int sign)
Emil.GMP.BigInt.BigInt(byte[] value, int sign)
Emil.GMP.BigInt.BigInt(byte[] value)
Emil.GMP.BigInt.BigInt(uint[] value, int sign)
Emil.GMP.BigInt.BigInt(uint[] value)
Emil.GMP.BigInt.BigInt(string s)
Emil.GMP.BigInt.BigInt(string s, int @base)
BigInt Emil.GMP.BigInt.ChangeBit(int bitIndex, int value)
BigInt Emil.GMP.BigInt.Negate()
BigInt Emil.GMP.BigInt.Complement()
BigInt Emil.GMP.BigInt.Add(BigInt x)
BigInt Emil.GMP.BigInt.Add(int x)
BigInt Emil.GMP.BigInt.Add(uint x)
BigInt Emil.GMP.BigInt.Subtract(BigInt x)
BigInt Emil.GMP.BigInt.Subtract(int x)
BigInt Emil.GMP.BigInt.Subtract(uint x)
BigInt Emil.GMP.BigInt.Multiply(BigInt x)
BigInt Emil.GMP.BigInt.Multiply(int x)
BigInt Emil.GMP.BigInt.Multiply(uint x)
BigInt Emil.GMP.BigInt.Square()
BigInt Emil.GMP.BigInt.Divide(BigInt x)
BigInt Emil.GMP.BigInt.Divide(int x)
BigInt Emil.GMP.BigInt.Divide(uint x)
BigInt Emil.GMP.BigInt.Divide(BigInt x, out BigInt remainder)
BigInt Emil.GMP.BigInt.Divide(int x, out BigInt remainder)
BigInt Emil.GMP.BigInt.Divide(int x, out int remainder)
BigInt Emil.GMP.BigInt.Divide(uint x, out BigInt remainder)
BigInt Emil.GMP.BigInt.Divide(uint x, out uint remainder)
BigInt Emil.GMP.BigInt.Divide(uint x, out int remainder)
BigInt Emil.GMP.BigInt.Remainder(BigInt x)
bool Emil.GMP.BigInt.IsDivisibleBy(BigInt x)
bool Emil.GMP.BigInt.IsDivisibleBy(int x)
bool Emil.GMP.BigInt.IsDivisibleBy(uint x)
BigInt Emil.GMP.BigInt.DivideExactly(BigInt x)
Divides exactly. Only works when the division is gauranteed to be exact (there is no remainder).
x
BigInt Emil.GMP.BigInt.DivideExactly(int x)
BigInt Emil.GMP.BigInt.DivideExactly(uint x)
BigInt Emil.GMP.BigInt.DivideMod(BigInt x, BigInt mod)
References Emil.GMP.BigInt::InvertMod.
BigInt Emil.GMP.BigInt.And(BigInt x)
BigInt Emil.GMP.BigInt.Or(BigInt x)
BigInt Emil.GMP.BigInt.Xor(BigInt x)
BigInt Emil.GMP.BigInt.Mod(BigInt mod)
BigInt Emil.GMP.BigInt.Mod(int mod)
BigInt Emil.GMP.BigInt.Mod(uint mod)
int Emil.GMP.BigInt.ModAsInt32(int mod)
uint Emil.GMP.BigInt.ModAsUInt32(uint mod)
BigInt Emil.GMP.BigInt.ShiftLeft(int shiftAmount)
BigInt Emil.GMP.BigInt.ShiftRight(int shiftAmount)
BigInt Emil.GMP.BigInt.PowerMod(BigInt exponent, BigInt mod)
BigInt Emil.GMP.BigInt.PowerMod(int exponent, BigInt mod)
BigInt Emil.GMP.BigInt.PowerMod(uint exponent, BigInt mod)
References Emil.GMP.BigInt::InvertMod.
BigInt Emil.GMP.BigInt.Power(int exponent)
BigInt Emil.GMP.BigInt.Power(uint exponent)
BigInt Emil.GMP.BigInt.InvertMod(BigInt mod)
Referenced by Emil.GMP.BigInt::DivideMod, Emil.GMP.BigInt::PowerMod.
bool Emil.GMP.BigInt.TryInvertMod(BigInt mod, out BigInt result)
bool Emil.GMP.BigInt.InverseModExists(BigInt mod)
BigInt Emil.GMP.BigInt.Sqrt()
BigInt Emil.GMP.BigInt.Sqrt(out BigInt remainder)
BigInt Emil.GMP.BigInt.Sqrt(out bool isExact)
BigInt Emil.GMP.BigInt.Root(int n)
BigInt Emil.GMP.BigInt.Root(uint n)
BigInt Emil.GMP.BigInt.Root(int n, out bool isExact)
BigInt Emil.GMP.BigInt.Root(uint n, out bool isExact)
BigInt Emil.GMP.BigInt.Root(int n, out BigInt remainder)
BigInt Emil.GMP.BigInt.Root(uint n, out BigInt remainder)
bool Emil.GMP.BigInt.IsPerfectSquare()
bool Emil.GMP.BigInt.IsPerfectPower()
bool Emil.GMP.BigInt.IsProbablyPrimeRabinMiller(int repetitions)
Uses the Rabin-Miller primality test to determine if the number is prime.
repetitions
BigInt Emil.GMP.BigInt.NextPrimeGMP()
BigInt Emil.GMP.BigInt.RemoveFactor(BigInt factor)
BigInt Emil.GMP.BigInt.RemoveFactor(BigInt factor, out int count)
int Emil.GMP.BigInt.CountOnes()
int Emil.GMP.BigInt.HammingDistance(BigInt x, BigInt y)
int Emil.GMP.BigInt.IndexOfZero(int startingIndex)
int Emil.GMP.BigInt.IndexOfOne(int startingIndex)
unsafe override int Emil.GMP.BigInt.GetHashCode()
bool Emil.GMP.BigInt.Equals(BigInt other)
override bool Emil.GMP.BigInt.Equals(object obj)
bool Emil.GMP.BigInt.Equals(int other)
bool Emil.GMP.BigInt.Equals(uint other)
bool Emil.GMP.BigInt.Equals(long other)
bool Emil.GMP.BigInt.Equals(ulong other)
bool Emil.GMP.BigInt.Equals(double other)
bool Emil.GMP.BigInt.Equals(decimal other)
bool Emil.GMP.BigInt.EqualsMod(BigInt x, BigInt mod)
bool Emil.GMP.BigInt.EqualsMod(int x, int mod)
bool Emil.GMP.BigInt.EqualsMod(uint x, uint mod)
int Emil.GMP.BigInt.CompareTo(object obj)
Referenced by Emil.GMP.BigInt::Compare, Emil.GMP.BigInt::operator!=, Emil.GMP.BigInt::operator<, Emil.GMP.BigInt::operator<=, Emil.GMP.BigInt::operator==, Emil.GMP.BigInt::operator>, Emil.GMP.BigInt::operator>=.
int Emil.GMP.BigInt.CompareTo(BigInt other)
int Emil.GMP.BigInt.CompareTo(int other)
int Emil.GMP.BigInt.CompareTo(uint other)
int Emil.GMP.BigInt.CompareTo(long other)
int Emil.GMP.BigInt.CompareTo(ulong other)
int Emil.GMP.BigInt.CompareTo(float other)
int Emil.GMP.BigInt.CompareTo(double other)
int Emil.GMP.BigInt.CompareTo(decimal other)
int Emil.GMP.BigInt.CompareAbsTo(object obj)
Referenced by Emil.GMP.BigInt::CompareAbs.
int Emil.GMP.BigInt.CompareAbsTo(BigInt other)
int Emil.GMP.BigInt.CompareAbsTo(int other)
int Emil.GMP.BigInt.CompareAbsTo(uint other)
int Emil.GMP.BigInt.CompareAbsTo(long other)
int Emil.GMP.BigInt.CompareAbsTo(ulong other)
int Emil.GMP.BigInt.CompareAbsTo(double other)
int Emil.GMP.BigInt.CompareAbsTo(decimal other)
BigInt Emil.GMP.BigInt.Clone()
byte [] Emil.GMP.BigInt.ToByteArray()
byte [] Emil.GMP.BigInt.ToByteArray(out int sign)
uint [] Emil.GMP.BigInt.ToUIntArray()
uint [] Emil.GMP.BigInt.ToUIntArray(out int sign)
override string Emil.GMP.BigInt.ToString()
Referenced by Emil.GMP.BigInt::operator string.
string Emil.GMP.BigInt.ToString(int @base)
static BigInt Emil.GMP.BigInt.operator-(BigInt x)
static BigInt Emil.GMP.BigInt.operator~(BigInt x)
static BigInt Emil.GMP.BigInt.operator+(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator+(BigInt x, int y)
static BigInt Emil.GMP.BigInt.operator+(int x, BigInt y)
static BigInt Emil.GMP.BigInt.operator+(BigInt x, uint y)
static BigInt Emil.GMP.BigInt.operator+(uint x, BigInt y)
static BigInt Emil.GMP.BigInt.operator-(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator-(int x, BigInt y)
static BigInt Emil.GMP.BigInt.operator-(BigInt x, int y)
static BigInt Emil.GMP.BigInt.operator-(uint x, BigInt y)
static BigInt Emil.GMP.BigInt.operator-(BigInt x, uint y)
static BigInt Emil.GMP.BigInt.operator++(BigInt x)
static BigInt Emil.GMP.BigInt.operator--(BigInt x)
static BigInt Emil.GMP.BigInt.operator*(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator*(int x, BigInt y)
static BigInt Emil.GMP.BigInt.operator*(BigInt x, int y)
static BigInt Emil.GMP.BigInt.operator*(uint x, BigInt y)
static BigInt Emil.GMP.BigInt.operator*(BigInt x, uint y)
static BigInt Emil.GMP.BigInt.operator/(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator/(BigInt x, int y)
static BigInt Emil.GMP.BigInt.operator/(BigInt x, uint y)
static BigInt Emil.GMP.BigInt.operator&(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator|(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator^(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.operator%(BigInt x, BigInt mod)
static BigInt Emil.GMP.BigInt.operator%(BigInt x, int mod)
static BigInt Emil.GMP.BigInt.operator%(BigInt x, uint mod)
static bool Emil.GMP.BigInt.operator<(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(long x, BigInt y)
static bool Emil.GMP.BigInt.operator<(BigInt x, long y)
static bool Emil.GMP.BigInt.operator<(ulong x, BigInt y)
static bool Emil.GMP.BigInt.operator<(BigInt x, ulong y)
static bool Emil.GMP.BigInt.operator<(float x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(BigInt x, float y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(long x, BigInt y)
static bool Emil.GMP.BigInt.operator<=(BigInt x, long y)
static bool Emil.GMP.BigInt.operator<=(ulong x, BigInt y)
static bool Emil.GMP.BigInt.operator<=(BigInt x, ulong y)
static bool Emil.GMP.BigInt.operator<=(float x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(BigInt x, float y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator<=(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(long x, BigInt y)
static bool Emil.GMP.BigInt.operator>(BigInt x, long y)
static bool Emil.GMP.BigInt.operator>(ulong x, BigInt y)
static bool Emil.GMP.BigInt.operator>(BigInt x, ulong y)
static bool Emil.GMP.BigInt.operator>(float x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(BigInt x, float y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(long x, BigInt y)
static bool Emil.GMP.BigInt.operator>=(BigInt x, long y)
static bool Emil.GMP.BigInt.operator>=(ulong x, BigInt y)
static bool Emil.GMP.BigInt.operator>=(BigInt x, ulong y)
static bool Emil.GMP.BigInt.operator>=(float x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(BigInt x, float y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator>=(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static BigInt Emil.GMP.BigInt.operator<<(BigInt x, int shiftAmount)
static BigInt Emil.GMP.BigInt.operator>>(BigInt x, int shiftAmount)
static BigInt Emil.GMP.BigInt.Power(int x, int exponent)
static BigInt Emil.GMP.BigInt.Power(uint x, uint exponent)
static BigInt Emil.GMP.BigInt.Gcd(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.Gcd(BigInt x, int y)
static BigInt Emil.GMP.BigInt.Gcd(int x, BigInt y)
static BigInt Emil.GMP.BigInt.Gcd(BigInt x, uint y)
static BigInt Emil.GMP.BigInt.Gcd(uint x, BigInt y)
static BigInt Emil.GMP.BigInt.Gcd(BigInt x, BigInt y, out BigInt a, out BigInt b)
static BigInt Emil.GMP.BigInt.Gcd(BigInt x, BigInt y, out BigInt a)
static BigInt Emil.GMP.BigInt.Lcm(BigInt x, BigInt y)
static BigInt Emil.GMP.BigInt.Lcm(BigInt x, int y)
static BigInt Emil.GMP.BigInt.Lcm(int x, BigInt y)
static BigInt Emil.GMP.BigInt.Lcm(BigInt x, uint y)
static BigInt Emil.GMP.BigInt.Lcm(uint x, BigInt y)
static int Emil.GMP.BigInt.LegendreSymbol(BigInt x, BigInt primeY)
static int Emil.GMP.BigInt.JacobiSymbol(BigInt x, BigInt y)
References Emil.GMP.BigInt::IsEven.
static int Emil.GMP.BigInt.JacobiSymbol(BigInt x, int y)
static int Emil.GMP.BigInt.JacobiSymbol(int x, BigInt y)
References Emil.GMP.BigInt::IsEven.
static int Emil.GMP.BigInt.JacobiSymbol(BigInt x, uint y)
static int Emil.GMP.BigInt.JacobiSymbol(uint x, BigInt y)
References Emil.GMP.BigInt::IsEven.
static int Emil.GMP.BigInt.KroneckerSymbol(BigInt x, BigInt y)
static int Emil.GMP.BigInt.KroneckerSymbol(BigInt x, int y)
static int Emil.GMP.BigInt.KroneckerSymbol(int x, BigInt y)
static int Emil.GMP.BigInt.KroneckerSymbol(BigInt x, uint y)
static int Emil.GMP.BigInt.KroneckerSymbol(uint x, BigInt y)
static BigInt Emil.GMP.BigInt.Factorial(int x)
static BigInt Emil.GMP.BigInt.Factorial(uint x)
static BigInt Emil.GMP.BigInt.Binomial(BigInt n, uint k)
static BigInt Emil.GMP.BigInt.Binomial(BigInt n, int k)
static BigInt Emil.GMP.BigInt.Binomial(uint n, uint k)
static BigInt Emil.GMP.BigInt.Binomial(int n, int k)
static BigInt Emil.GMP.BigInt.Fibonacci(int n)
static BigInt Emil.GMP.BigInt.Fibonacci(uint n)
static BigInt Emil.GMP.BigInt.Fibonacci(int n, out BigInt previous)
static BigInt Emil.GMP.BigInt.Fibonacci(uint n, out BigInt previous)
static BigInt Emil.GMP.BigInt.Lucas(int n)
static BigInt Emil.GMP.BigInt.Lucas(uint n)
static BigInt Emil.GMP.BigInt.Lucas(int n, out BigInt previous)
static BigInt Emil.GMP.BigInt.Lucas(uint n, out BigInt previous)
static bool Emil.GMP.BigInt.operator==(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(long x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, long y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(ulong x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, ulong y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(float x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, float y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator==(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(long x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, long y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(ulong x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, ulong y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(float x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, float y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static bool Emil.GMP.BigInt.operator!=(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, object y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(object x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, int y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(int x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, uint y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(uint x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, long y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(long x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, ulong y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(ulong x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, double y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(double x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.Compare(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, object y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(object x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, int y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(int x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, uint y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(uint x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, long y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(long x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, ulong y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(ulong x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, double y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(double x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(BigInt x, decimal y)
References Emil.GMP.BigInt::CompareAbsTo.
static int Emil.GMP.BigInt.CompareAbs(decimal x, BigInt y)
References Emil.GMP.BigInt::CompareAbsTo.
static implicit Emil.GMP.BigInt.operator BigInt(byte value)
static implicit Emil.GMP.BigInt.operator BigInt(int value)
static implicit Emil.GMP.BigInt.operator BigInt(uint value)
static implicit Emil.GMP.BigInt.operator BigInt(short value)
static implicit Emil.GMP.BigInt.operator BigInt(ushort value)
static implicit Emil.GMP.BigInt.operator BigInt(long value)
static implicit Emil.GMP.BigInt.operator BigInt(ulong value)
static implicit Emil.GMP.BigInt.operator BigInt(float value)
static implicit Emil.GMP.BigInt.operator BigInt(double value)
static implicit Emil.GMP.BigInt.operator BigInt(decimal value)
static Emil.GMP.BigInt.operator BigInt(string value)
static Emil.GMP.BigInt.operator byte(BigInt value)
static Emil.GMP.BigInt.operator int(BigInt value)
static Emil.GMP.BigInt.operator uint(BigInt value)
static Emil.GMP.BigInt.operator short(BigInt value)
static Emil.GMP.BigInt.operator ushort(BigInt value)
static Emil.GMP.BigInt.operator long(BigInt value)
static Emil.GMP.BigInt.operator ulong(BigInt value)
static Emil.GMP.BigInt.operator float(BigInt value)
static Emil.GMP.BigInt.operator double(BigInt value)
static Emil.GMP.BigInt.operator decimal(BigInt value)
static Emil.GMP.BigInt.operator string(BigInt value)
References Emil.GMP.BigInt::ToString.
static unsafe bool Emil.GMP.BigInt.IsZero(uint[] x)
static unsafe bool Emil.GMP.BigInt.IsZero(byte[] x)