.TH "Alaris::Extras::HaskellEvaluator" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Extras::HaskellEvaluator \- 
.PP
A class which provides methods to compile and run arbitrary Haskell code.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHaskellEvaluator\fP (ref \fBAlarisBot\fP bot)"
.br
.RI "\fIInitializes a new instance of \fBHaskellEvaluator\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class which provides methods to compile and run arbitrary Haskell code. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alaris.Extras.HaskellEvaluator.HaskellEvaluator (ref \fBAlarisBot\fP bot)"
.PP
Initializes a new instance of \fBHaskellEvaluator\fP \fBParameters:\fP
.RS 4
\fIbot\fP The bot instance. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
