.TH "Alaris::Core::Log" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Core::Log \- 
.PP
Logging class used all across \fBAlaris\fP.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBNotice\fP (string module, string message)"
.br
.RI "\fIEmit a console notice. \fP"
.ti -1c
.RI "static void \fBDebug\fP (string module, string message)"
.br
.RI "\fIEmit a console debug message. \fP"
.ti -1c
.RI "static void \fBError\fP (string module, string message)"
.br
.RI "\fIEmit a console error. \fP"
.ti -1c
.RI "static void \fBSuccess\fP (string module, string message)"
.br
.RI "\fIEmit a console success message. \fP"
.ti -1c
.RI "static void \fBLargeWarning\fP (string message)"
.br
.RI "\fIEmit a large warning message. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Logging class used all across \fBAlaris\fP. 


.SH "Member Function Documentation"
.PP 
.SS "static void Alaris.Core.Log.Debug (string module, string message)\fC [static]\fP"
.PP
Emit a console debug message. \fBParameters:\fP
.RS 4
\fImodule\fP The module name where the thing described in the message happened. 
.br
\fImessage\fP The message to display. 
.RE
.PP

.SS "static void Alaris.Core.Log.Error (string module, string message)\fC [static]\fP"
.PP
Emit a console error. \fBParameters:\fP
.RS 4
\fImodule\fP The module name where the thing described in the message happened. 
.br
\fImessage\fP The message to display. 
.RE
.PP

.SS "static void Alaris.Core.Log.LargeWarning (string message)\fC [static]\fP"
.PP
Emit a large warning message. \fBParameters:\fP
.RS 4
\fImessage\fP The message to display. 
.RE
.PP

.SS "static void Alaris.Core.Log.Notice (string module, string message)\fC [static]\fP"
.PP
Emit a console notice. \fBParameters:\fP
.RS 4
\fImodule\fP The module name where the thing described in the message happened. 
.br
\fImessage\fP The message to display. 
.RE
.PP

.SS "static void Alaris.Core.Log.Success (string module, string message)\fC [static]\fP"
.PP
Emit a console success message. \fBParameters:\fP
.RS 4
\fImodule\fP The module name where the thing described in the message happened. 
.br
\fImessage\fP The message to display. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
