.TH "Alaris::Irc::CommandBuilder" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Irc::CommandBuilder \- 
.PP
\fBCommandBuilder\fP provides the support methods needed by its subclasses to build correctly formatted messages for the IRC server. It is never itself instantiated.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAlaris.Irc.CtcpSender\fP, and \fBAlaris.Irc.Sender\fP.
.SH "Detailed Description"
.PP 
\fBCommandBuilder\fP provides the support methods needed by its subclasses to build correctly formatted messages for the IRC server. It is never itself instantiated. 



.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
