.TH "Alaris::Extras::ConfigFileInvalidException" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Extras::ConfigFileInvalidException \- 
.PP
Exception thrown when an invalid config file is detected.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigFileInvalidException\fP ()"
.br
.RI "\fICreates a new instance of \fBConfigFileInvalidException\fP \fP"
.ti -1c
.RI "\fBConfigFileInvalidException\fP (string msg)"
.br
.RI "\fICreates a new instance of \fBConfigFileInvalidException\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
Exception thrown when an invalid config file is detected. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alaris.Extras.ConfigFileInvalidException.ConfigFileInvalidException ()"
.PP
Creates a new instance of \fBConfigFileInvalidException\fP 
.SS "Alaris.Extras.ConfigFileInvalidException.ConfigFileInvalidException (string msg)"
.PP
Creates a new instance of \fBConfigFileInvalidException\fP \fBParameters:\fP
.RS 4
\fImsg\fP The message of the exception. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
