.TH "Alaris::Irc::DccFileSessionManager" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Irc::DccFileSessionManager \- 
.PP
This class checks each file session to see if it has not had any activity within the timeout period so that inactive sessions can be closed.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBDccFileSessionManager\fP \fBDefaultInstance\fP\fC [get]\fP"
.br
.RI "\fIReturns the singleton instance. \fP"
.ti -1c
.RI "long \fBTimeoutPeriod\fP\fC [get, set]\fP"
.br
.RI "\fITimeout period in milliseconds. \fP"
.in -1c
.SH "Detailed Description"
.PP 
This class checks each file session to see if it has not had any activity within the timeout period so that inactive sessions can be closed. 


.SH "Property Documentation"
.PP 
.SS "\fBDccFileSessionManager\fP Alaris.Irc.DccFileSessionManager.DefaultInstance\fC [static, get]\fP"
.PP
Returns the singleton instance. 
.SS "long Alaris.Irc.DccFileSessionManager.TimeoutPeriod\fC [get, set]\fP"
.PP
Timeout period in milliseconds. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
