.TH "Alaris::Irc::NameGenerator" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Irc::NameGenerator \- 
.PP
Generates random, made-up names. The names appear to be language neutral (sort of).  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameGenerator\fP ()"
.br
.RI "\fICreate an instance. \fP"
.ti -1c
.RI "string \fBMakeName\fP ()"
.br
.RI "\fIGenerates a name randomly using certain construction rules. The name will be different each time it is called. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generates random, made-up names. The names appear to be language neutral (sort of). 

This is a port of the orginal Javascript written by John Ahlschwede, ahlschwede@hotmail.com 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alaris.Irc.NameGenerator.NameGenerator ()"
.PP
Create an instance. 
.SH "Member Function Documentation"
.PP 
.SS "string Alaris.Irc.NameGenerator.MakeName ()"
.PP
Generates a name randomly using certain construction rules. The name will be different each time it is called. \fBReturns:\fP
.RS 4
A name string.
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
