.TH "Alaris::MainPlugin::AlarisPlugin" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::MainPlugin::AlarisPlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAlaris::Core::IAlarisBasic\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlarisPlugin\fP ()"
.br
.ti -1c
.RI "void \fBInitialize\fP (ref \fBConnection\fP con)"
.br
.ti -1c
.RI "void \fBInitialize\fP (ref \fBConnection\fP con, ref List< string > a)"
.br
.ti -1c
.RI "void \fBOnPublicMessage\fP (\fBUserInfo\fP user, string chan, string msg)"
.br
.ti -1c
.RI "void \fBOnRegistered\fP ()"
.br
.ti -1c
.RI "void \fBOnUnload\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "string \fBGetName\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alaris.MainPlugin.AlarisPlugin.AlarisPlugin ()"
.SH "Member Function Documentation"
.PP 
.SS "string Alaris.MainPlugin.AlarisPlugin.GetName ()"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.
.SS "void Alaris.MainPlugin.AlarisPlugin.Initialize (ref \fBConnection\fP con, ref List< string > a)"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.
.SS "void Alaris.MainPlugin.AlarisPlugin.Initialize (ref \fBConnection\fP con)"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.
.SS "void Alaris.MainPlugin.AlarisPlugin.OnLoad ()"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.
.SS "void Alaris.MainPlugin.AlarisPlugin.OnPublicMessage (\fBUserInfo\fP user, string chan, string msg)"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.
.SS "void Alaris.MainPlugin.AlarisPlugin.OnRegistered ()"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.
.SS "void Alaris.MainPlugin.AlarisPlugin.OnUnload ()"
.PP
Implements \fBAlaris.Core.IAlarisBasic\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
