.TH "Alaris::Extras::WebHelper" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Extras::WebHelper \- 
.PP
A class which provides useful methods for working with the world-wide web.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetWebTitle\fP (Uri url)"
.br
.RI "\fIGets the title of the specified webpage. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class which provides useful methods for working with the world-wide web. 


.SH "Member Function Documentation"
.PP 
.SS "static string Alaris.Extras.WebHelper.GetWebTitle (Uri url)\fC [static]\fP"
.PP
Gets the title of the specified webpage. \fBParameters:\fP
.RS 4
\fIurl\fP The webpage's URL. 
.RE
.PP
\fBReturns:\fP
.RS 4
The webpage's title. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
