.TH "Alaris" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBCore\fP"
.br
.ti -1c
.RI "package \fBExtras\fP"
.br
.ti -1c
.RI "package \fBIrc\fP"
.br
.ti -1c
.RI "package \fBLuaPlugin\fP"
.br
.ti -1c
.RI "package \fBMainPlugin\fP"
.br
.ti -1c
.RI "package \fBMangosRssPlugin\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
