.TH "Alaris::Core::IAlarisBasic" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Core::IAlarisBasic \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAlaris.LuaPlugin.AlarisPlugin\fP, \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP (ref \fBConnection\fP con)"
.br
.ti -1c
.RI "void \fBInitialize\fP (ref \fBConnection\fP con, ref List< string > channels)"
.br
.ti -1c
.RI "void \fBOnPublicMessage\fP (\fBUserInfo\fP user, string channel, string msg)"
.br
.ti -1c
.RI "void \fBOnRegistered\fP ()"
.br
.ti -1c
.RI "void \fBOnLoad\fP ()"
.br
.ti -1c
.RI "void \fBOnUnload\fP ()"
.br
.ti -1c
.RI "string \fBGetName\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string Alaris.Core.IAlarisBasic.GetName ()"
.PP
Implemented in \fBAlaris.LuaPlugin.AlarisPlugin\fP, \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "void Alaris.Core.IAlarisBasic.Initialize (ref \fBConnection\fP con, ref List< string > channels)"
.PP
Implemented in \fBAlaris.LuaPlugin.AlarisPlugin\fP, \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "void Alaris.Core.IAlarisBasic.Initialize (ref \fBConnection\fP con)"
.PP
Implemented in \fBAlaris.LuaPlugin.AlarisPlugin\fP, \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "void Alaris.Core.IAlarisBasic.OnLoad ()"
.PP
Implemented in \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "void Alaris.Core.IAlarisBasic.OnPublicMessage (\fBUserInfo\fP user, string channel, string msg)"
.PP
Implemented in \fBAlaris.LuaPlugin.AlarisPlugin\fP, \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "void Alaris.Core.IAlarisBasic.OnRegistered ()"
.PP
Implemented in \fBAlaris.LuaPlugin.AlarisPlugin\fP, \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.
.SS "void Alaris.Core.IAlarisBasic.OnUnload ()"
.PP
Implemented in \fBAlaris.MainPlugin.AlarisPlugin\fP, and \fBAlaris.MangosRssPlugin.AlarisPlugin\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
