.TH "Alaris::Extras::CrashHandler" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Alaris::Extras::CrashHandler \- 
.PP
A class providing functions to run specific method in an exception-handled environment.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCrashHandler\fP ()"
.br
.RI "\fICreates a new instance of \fBCrashHandler\fP \fP"
.ti -1c
.RI "void \fBHandleReadConfig\fP (ReadConfigDelegate confread, string param, ref List< Exception > caught)"
.br
.RI "\fIExecutes the specified \fBReadConfig\fP method in an exception-safe environment. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A class providing functions to run specific method in an exception-handled environment. 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Alaris.Extras.CrashHandler.CrashHandler ()"
.PP
Creates a new instance of \fBCrashHandler\fP 
.SH "Member Function Documentation"
.PP 
.SS "void Alaris.Extras.CrashHandler.HandleReadConfig (ReadConfigDelegate confread, string param, ref List< Exception > caught)"
.PP
Executes the specified \fBReadConfig\fP method in an exception-safe environment. \fBParameters:\fP
.RS 4
\fIconfread\fP The ReadConfig method. 
.br
\fIparam\fP The parameter passed to the ReadConfig method. 
.br
\fIcaught\fP A list filled which will be filled with the exceptions caught inside the method. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
