.TH "irc/Ctcp/CtcpSender.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc/Ctcp/CtcpSender.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlaris.Irc.CtcpSender\fP"
.br
.RI "\fIThis class allows the client to send CTCP commands. There is no limit on what commands can actually be sent, however, the accepted CTCP commands are: \fBUserInfo\fP, Finger, Version, Source, ClientInfo, ErrMsg, and Time. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Irc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
