.TH "irc/Ctcp/CtcpListener.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc/Ctcp/CtcpListener.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlaris.Irc.CtcpListener\fP"
.br
.RI "\fIThis class is used to send CTCP specific events. Once registered with this object the client can receive notification of all CTCP requests, pings, and replies. Instances of this class are not created directly but are retrieved as a property from a \fBConnection\fP object. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Irc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
