.TH "irc/Dcc/DccListener.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc/Dcc/DccListener.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlaris.Irc.DccListener\fP"
.br
.RI "\fI\fBDccListener\fP listens for incoming DCC requests on any \fBConnection\fP in which DCC is enabled. This class follows the singleton pattern and there so there is only a single instance which listens to all connections. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Irc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
