.TH "irc/Enums.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc/Enums.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Irc\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAlaris::Irc.ModeAction\fP { \fBAlaris::Irc.Add\fP =  43, \fBAlaris::Irc.Remove\fP =  45 }"
.br
.RI "\fIWhether a mode has been added or removed. \fP"
.ti -1c
.RI "enum \fBAlaris::Irc.UserMode\fP { \fBAlaris::Irc.Away\fP =  97, \fBAlaris::Irc.Wallops\fP = 119, \fBAlaris::Irc.Invisible\fP = 105, \fBAlaris::Irc.Operator\fP = 111, \fBAlaris::Irc.Restricted\fP = 114, \fBAlaris::Irc.LocalOperator\fP =  79, \fBAlaris::Irc.ServerNotices\fP =  115 }"
.br
.RI "\fIThe possible user modes. \fP"
.ti -1c
.RI "enum \fBAlaris::Irc.ChannelMode\fP { \fBAlaris::Irc.ChannelCreator\fP =  79, \fBAlaris::Irc.ChannelOperator\fP =  111, \fBAlaris::Irc.HalfChannelOperator\fP =  104, \fBAlaris::Irc.Voice\fP =  118, \fBAlaris::Irc.Anonymous\fP =  97, \fBAlaris::Irc.InviteOnly\fP =  105, \fBAlaris::Irc.Moderated\fP =  109, \fBAlaris::Irc.NoOutside\fP =  110, \fBAlaris::Irc.Quiet\fP =  113, \fBAlaris::Irc.Private\fP =  112, \fBAlaris::Irc.Secret\fP =  115, \fBAlaris::Irc.ServerReop\fP =  114, \fBAlaris::Irc.TopicSettable\fP =  116, \fBAlaris::Irc.Password\fP =  107, \fBAlaris::Irc.UserLimit\fP =  108, \fBAlaris::Irc.Ban\fP =  98, \fBAlaris::Irc.Exception\fP =  101, \fBAlaris::Irc.Invitation\fP =  73 }"
.br
.RI "\fIPossible channel modes. \fP"
.ti -1c
.RI "enum \fBAlaris::Irc.StatsQuery\fP { \fBAlaris::Irc.Connections\fP =  108, \fBAlaris::Irc.CommandUsage\fP =  109, \fBAlaris::Irc.Operators\fP =  111, \fBAlaris::Irc.Uptime\fP =  117 }"
.br
.RI "\fIThe possible stats message query parameters. \fP"
.ti -1c
.RI "enum \fBAlaris::Irc.MircColor\fP { \fBAlaris::Irc.White\fP =  0, \fBAlaris::Irc.Black\fP =  1, \fBAlaris::Irc.Blue\fP =  2, \fBAlaris::Irc.Green\fP =  3, \fBAlaris::Irc.LightRed\fP =  4, \fBAlaris::Irc.Brown\fP =  5, \fBAlaris::Irc.Purple\fP =  6, \fBAlaris::Irc.Orange\fP =  7, \fBAlaris::Irc.Yellow\fP =  8, \fBAlaris::Irc.LightGreen\fP =  9, \fBAlaris::Irc.Cyan\fP =  10, \fBAlaris::Irc.LightCyan\fP =  11, \fBAlaris::Irc.LightBlue\fP =  12, \fBAlaris::Irc.Pink\fP =  13, \fBAlaris::Irc.Grey\fP =  14, \fBAlaris::Irc.LightGrey\fP =  15, \fBAlaris::Irc.Transparent\fP =  99 }"
.br
.RI "\fIAll recognized mIRC colors. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
