.TH "irc/Identd.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc/Identd.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlaris.Irc.Identd\fP"
.br
.RI "\fIAn Ident daemon is still used by some IRC networks for authentication. It is a simple service which when queried by a remote system returns a username. The server is controlled via static methods all of which are Thread safe. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Irc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
