.TH "irc/Sender.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
irc/Sender.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlaris.Irc.Sender\fP"
.br
.RI "\fIThis class is used to send all the IRC commands except for CTCP and DCC messages. Instances of this class are retrieved as properties of the \fBConnection\fP object. All methods in this class are thread safe. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Irc\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
