.TH "alaris/Utilities.cs" 3 "25 May 2010" "Version 1.6" "Alaris IRC Bot" \" -*- nroff -*-
.ad l
.nh
.SH NAME
alaris/Utilities.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlaris.Extras.Utilities\fP"
.br
.RI "\fIClass providing useful methods for handling different things. \fP"
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBAlaris.Extras\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Alaris IRC Bot from the source code.
