//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;

namespace Alaris.Xml
{ // 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    [XmlRootAttribute(Namespace="http://github.com/Twl/alaris", IsNullable=false, ElementName = "Alaris")]
    public class AlarisConfig {
    
        private Config configField;
    
        /// <remarks/>
        public Config Config {
            get {
                return this.configField;
            }
            set {
                this.configField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public class Config {
    
        private Irc ircField;
    
        private string databaseField;
    
        private Scripts scriptsField;
    
        private Addons addonsField;
    
        private Localization localizationField;
    
        private Remote remoteField;
    
        private CLI cLIField;
    
        /// <remarks/>
        public Irc Irc {
            get {
                return this.ircField;
            }
            set {
                this.ircField = value;
            }
        }
    
        /// <remarks/>
        public string Database {
            get {
                return this.databaseField;
            }
            set {
                this.databaseField = value;
            }
        }
    
        /// <remarks/>
        public Scripts Scripts {
            get {
                return this.scriptsField;
            }
            set {
                this.scriptsField = value;
            }
        }
    
        /// <remarks/>
        public Addons Addons {
            get {
                return this.addonsField;
            }
            set {
                this.addonsField = value;
            }
        }
    
        /// <remarks/>
        public Localization Localization {
            get {
                return this.localizationField;
            }
            set {
                this.localizationField = value;
            }
        }
    
        /// <remarks/>
        public Remote Remote {
            get {
                return this.remoteField;
            }
            set {
                this.remoteField = value;
            }
        }
    
        /// <remarks/>
        public CLI CLI {
            get {
                return this.cLIField;
            }
            set {
                this.cLIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class Irc {
    
        private string serverField;
    
        private string nicknameField;
    
        private NickServ nickServField;
    
        private string channelsField;
    
        private Admin adminField;
    
        /// <remarks/>
        public string Server {
            get {
                return this.serverField;
            }
            set {
                this.serverField = value;
            }
        }
    
        /// <remarks/>
        public string Nickname {
            get {
                return this.nicknameField;
            }
            set {
                this.nicknameField = value;
            }
        }
    
        /// <remarks/>
        public NickServ NickServ {
            get {
                return this.nickServField;
            }
            set {
                this.nickServField = value;
            }
        }
    
        /// <remarks/>
        public string Channels {
            get {
                return this.channelsField;
            }
            set {
                this.channelsField = value;
            }
        }
    
        /// <remarks/>
        public Admin Admin {
            get {
                return this.adminField;
            }
            set {
                this.adminField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class NickServ {
    
        private bool enabledField;
    
        private string passwordField;
    
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class CLI {
    
        private bool enabledField;
    
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class Remote {
    
        private int portField;
    
        private string nameField;
    
        private string passwordField;
    
        /// <remarks/>
        public int Port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
    
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class Localization {
    
        private string localeField;
    
        /// <remarks/>
        public string Locale {
            get {
                return this.localeField;
            }
            set {
                this.localeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class Addons {
    
        private bool enabledField;
    
        private string directoryField;
    
        /// <remarks/>
        public bool Enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
            }
        }
    
        /// <remarks/>
        public string Directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class Scripts {
    
        private bool luaField;
    
        private string directoryField;
    
        private string additionalReferencesField;
    
        /// <remarks/>
        public bool Lua {
            get {
                return this.luaField;
            }
            set {
                this.luaField = value;
            }
        }
    
        /// <remarks/>
        public string Directory {
            get {
                return this.directoryField;
            }
            set {
                this.directoryField = value;
            }
        }
    
        /// <remarks/>
        public string AdditionalReferences {
            get {
                return this.additionalReferencesField;
            }
            set {
                this.additionalReferencesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://github.com/Twl/alaris")]
    public partial class Admin {
    
        private string nickField;
    
        private string userField;
    
        private string hostField;
    
        /// <remarks/>
        public string Nick {
            get {
                return this.nickField;
            }
            set {
                this.nickField = value;
            }
        }
    
        /// <remarks/>
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
    
        /// <remarks/>
        public string Host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
    }
}