Alaris::Irc::Dcc::DccChatSession
ChatRequestTimeoutEventHandler Alaris.Irc.Dcc.DccChatSession.OnChatRequestTimeout
The remote user did not respond to a Chat request within the timeout period.
ChatSessionOpenedEventHandler Alaris.Irc.Dcc.DccChatSession.OnChatSessionOpened
A chat session has been opened. This is called when a session has been opened regardless of who initiated the session.
ChatSessionClosedEventHandler Alaris.Irc.Dcc.DccChatSession.OnChatSessionClosed
The chat session has been closed by either participant.
ChatMessageReceivedEventHandler Alaris.Irc.Dcc.DccChatSession.OnChatMessageReceived
Text from the remote user was received.
const int Alaris.Irc.Dcc.DccChatSession.DefaultTimeout
readonly DccUserInfo Alaris.Irc.Dcc.DccChatSession.dccUserInfo
TcpClient Alaris.Irc.Dcc.DccChatSession.client
TcpListener Alaris.Irc.Dcc.DccChatSession.server
Thread Alaris.Irc.Dcc.DccChatSession.thread
int Alaris.Irc.Dcc.DccChatSession.listenPort
bool Alaris.Irc.Dcc.DccChatSession.listening
bool Alaris.Irc.Dcc.DccChatSession.receiving
bool Alaris.Irc.Dcc.DccChatSession.Connected
A read-only property indicating whether this session is currently connected to another user.
True if the client is connected.
DccUserInfo Alaris.Irc.Dcc.DccChatSession.ClientInfo
Iinformation about the remote user.
A read-only instance of DccUserInfo.
internal Alaris.Irc.Dcc.DccChatSession.DccChatSession(DccUserInfo dccUserInfo)
void Alaris.Irc.Dcc.DccChatSession.CloseClientConnection()
void Alaris.Irc.Dcc.DccChatSession.SendClosedEvent()
Send the session closed event.
void Alaris.Irc.Dcc.DccChatSession.SendChatRequest(string listenIpAddress, int port)
Create the correctly formatted DCC CHAT message and send it.
void Alaris.Irc.Dcc.DccChatSession.TimerExpired(object state)
Called when timeout thread is done. If the session has not yet not connected then stop listening and send a OnChatRequestTimeout event.
state An instance of DccChatSession
void Alaris.Irc.Dcc.DccChatSession.Listen()
void Alaris.Irc.Dcc.DccChatSession.Connect()
void Alaris.Irc.Dcc.DccChatSession.ReceiveMessages()
void Alaris.Irc.Dcc.DccChatSession.SendMessage(string text)
Send a line of text to the remote user. There is no fixed limit to message size but they should not be too long.
text The text. It need not have a newline at the end since one will automatically appended..
void Alaris.Irc.Dcc.DccChatSession.Close()
Close the chat session.
Referenced by Alaris.Irc.Dcc.DccChatSession::Dispose.
override string Alaris.Irc.Dcc.DccChatSession.ToString()
Summary information about this session.
Simple information about this session in human readable format.
Referenced by Alaris.Irc.Dcc.DccChatSession::Accept, Alaris.Irc.Dcc.DccChatSession::Request.
void Alaris.Irc.Dcc.DccChatSession.Dispose()
References Alaris.Irc.Dcc.DccChatSession::Close.
static DccChatSession Alaris.Irc.Dcc.DccChatSession.Accept(DccUserInfo dccUserInfo)
When another a remote user has sent a chat request, this method is called to accept the request and start a chat session with that user.
This method should be called from within a try/catch block because there are many things that could prevent this connection attempt from succeeding. dccUserInfo A collection of information about the remote user. The DccChatSession instance for this session.
References Alaris.Irc.Dcc.DccChatSession::ToString.
static DccChatSession Alaris.Irc.Dcc.DccChatSession.Request(DccUserInfo dccUserInfo, string listenIPAddress, int listenPort)
Send a DCC Chat request to a remote user and use the default timeout period of 30 seconds.
If the user does not respond within the timeout period the DccChatSession will stop listening for a connection. The sesssion instance created then becomes invalid. This methods must be called again and a new instance created in order to initiate a try again. This method should be called from within a try/catch block in case there are socket errors. dccUserInfo A collection of information about the remote user. listenIPAddress The IP address of the local machine in dot quad format (e.g. 192.168.0.25). This is the address that will be sent to the remote user. The IP address of the NAT machine must be used if the client is behind a a NAT/Firewall system. listenPort The TCP/IP port to listen on
static DccChatSession Alaris.Irc.Dcc.DccChatSession.Request(DccUserInfo dccUserInfo, string listenIPAddress, int listenPort, long timeout)
Send a DCC Chat request to a remote user and wait for a connection using timeout period specified.
If the user does not respond within the timeout period the DccChatSession will stop listening for a connection. The sesssion instance created then becomes invalid. This methods must be called again and a new instance created in order to initiate a try again. This method should be called from within a try/catch block in case there are socket errors. dccUserInfo A collection of information about the remote user. listenIPAddress The IP address that will be sent to the remote user. It must be in dotted quad format (i.e. 192.168.0.2). If the client is behind a NAT system then this should be the address of that system and not the local host. listenPort The TCP/IP port to listen on timeout How long to wait for a response in milliseconds. A value of zero will disable the timeout.
References Alaris.Irc.Dcc.DccChatSession::ToString.